[[provider]]
provider = "github"
name = "rainmakerteam"
path = "github"
env_var = "GITHUB_TOKEN"
skip_forks = false

[[provider]]
provider = "github"
name = "anarkioteam"
path = "github"
env_var = "GITHUB_TOKEN"
skip_forks = false

[[provider]]
provider = "github"
name = "nickpellant"
path = "github"
env_var = "GITHUB_TOKEN"
skip_forks = false
